# Generated by Django 5.1.1 on 2024-09-19 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 23, 0, 11, 568383, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Publicación'),
        ),
    ]
