# Generated by Django 5.2.11 on 2026-03-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
