# Generated by Django 5.2.11 on 2026-03-07 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='update',
            new_name='updated_at',
        ),
    ]
