# Generated by Django 5.1.1 on 2024-09-27 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_oder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
        migrations.RenameField(
            model_name='page',
            old_name='oder',
            new_name='order',
        ),
    ]
